.TH QBANK 5
.SH NAME
qbank - file holding the questions data for \fIqserver\fR and \fIqclient\fR
.SH DESCRIPTION
.B qbank
is just a normal sqlite3 database file.  It's contents consist of three tables:
.TS
tab (@);
l lx.
1.@T{
Questions(Number INTEGER PRIMARY KEY ASC, Question TEXT, Correct TEXT);
T}
2.@T{
Tags(Number INTEGER PRIMARY KEY ASC, tag1 BLOB, tag2 BLOB, tag3 BLOB, tag4 BLOB, tag5 BLOB);
T}
3.@T{
Answers(Number INTEGER PRIMARY KEY ASC, A TEXT, B TEXT, C TEXT, D TEXT);
T}
.TE
.SH SEE ALSO
qserver(1), qclient(1)
.SH AUTHOR
John Parry, ogparry1@ufl.edu
